eureka:
  instance:
    prefer-ip-address: true
    appname: ${spring.application.name}
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      zone: primary # This is needed for the load balancer
      profile: ${spring.profiles.active}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    enabled: true
    healthcheck:
      enabled: true
    initial-instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
